# Allowed operators: Equal, NotEqual, Regex, GreaterThan, LowerThan
apiVersion: kube-shield.red-labs.co.uk/v1
kind: Policy #or ClusterPolicy
metadata:
  name: some-random-policy
spec:
  applyOn:
    - apiVersion: v1
      kind: Pod
  defaultBehaviour: IfMatchDeny
  rules:
  - name: rule-name
    checks:
    - field: $_.input.metadata.namespace
      operator: Regex
      value: 1
    # AND
    # - field: $_.input.spec.containers[_].resources.limits.memory
    #   operator: NotEqual
    #   value: $input.spec.container[_].resources.requests.memory
