apiVersion: kube-shield.red-labs.co.uk/v1
kind: Policy
metadata:
  name: deny-exec
spec:
  applyOn:
  - apiGroup: ""
    resource: "pods/exec"
    verb: "connect"
  rules:
  - name: rule-name
    script: |
      if request.namespace == "default" and request.name == "po" then
        return false, "pod 'po' contains sensitive information"
      else
        return true
      end
