# Allowed operators: Equal, NotEqual, Regex, GreaterThan, LowerThan
apiVersion: kube-shield.red-labs.co.uk/v1
kind: Policy #or ClusterPolicy
metadata:
  name: some-random-policy
spec:
  applyOn:
    - apiVersion: v1
      kind: Pod
  defaultBehaviour: IfMatchDeny
  rules:
  - name: rule-name
    data:
    - key: $input.metadata.namespace
      operator: Regex
      value: ^(kube-system|default)$
    # AND
    - key: $input.spec.containers[_].resources.limits.memory
      operator: NotEqual
      value: $input.spec.container[_].resources.requests.memory
  # OR
  - name: second-rule-name
    data:
    - key: $input.metadata.namespace
      operator: Regex
      value: ^(kube-system|default)$
    # AND
    - key: $input.spec.containers[_].resources.limits.memory
      operator: NotEqual
      value: $input.spec.container[_].resources.requests.memory
