apiVersion: kube-shield.red-labs.co.uk/v1
kind: Policy
metadata:
  name: security-rules-prod
spec:
  applyOn:
  - apiGroup: ""
    resource: "pods/exec"
    operation: "connect"
  rules:
  - name: deny-exec
    # request is a pre-populated variable with the value of the apiserver payload
    script: |
      errMsg = "you can't exec into pods unless specified in the policy"
      if request.namespace == "default" and request.name == "po" then
        return true, ""
      end
