apiVersion: kube-shield.red-labs.co.uk/v1
kind: Policy
metadata:
  name: deny-exec
spec:
  applyOn:
  - apiGroup: ""
    resource: "pods/exec"
    operation: "connect"
  rules:
  - name: protected-ns
    # request is a pre-populated variable with the value of the apiserver payload
    script: |
      if request.namespace == "default" and request.name == "po" then
        return true, ""
      else
        return false, 'you cannot exec into pods'
      end
