# Allowed operators: Equal, NotEqual, Regex, GreaterThan, LowerThan
apiVersion: kube-shield.red-labs.co.uk/v1
kind: Policy
metadata:
  name: deny-exec
spec:
  applyOn:
  - verb: connect
    group: ""
    resource: pods/exec 
  defaultBehaviour: DenyIfMatch
  rules:
  - name: rule-name
    checks:
    - field: $_.namespace
      operator: Equal
      value: default

    # AND
    # - field: $_.input.spec.containers[_].resources.limits.memory
    #   operator: NotEqual
    #   value: $input.spec.container[_].resources.requests.memory
