apiVersion: kube-shield.red-labs.co.uk/v1
kind: Policy
metadata:
  name: deny-exec
spec:
  applyOn:
  - verb: connect
    group: ""
    resource: pods/exec 
  defaultBehaviour: DenyIfMatch
  rules:
  - name: rule-name
    checks:
    - field: $_.namespace
      operator: Equal
      value: default
