apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "host.docker.internal"
webhooks:
- name: "host.docker.internal"
  rules:
  - apiGroups: [""]
    apiVersions: ["*"]
    operations: ["*"]
    resources: ["*/*"]
  clientConfig:
    url: "https://host.docker.internal:8000/validate"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFmTVIwd0d3WURWUVFERXhSelpXeG0KTFhOcFoyNWxaQzFyT0hNdFkyVnlkREFlRncweU1qRXlNVE15TXpJM01EQmFGdzB6TWpFeU1UQXlNekkzTURCYQpNQjh4SFRBYkJnTlZCQU1URkhObGJHWXRjMmxuYm1Wa0xXczRjeTFqWlhKME1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBJZ0VoZVM5NjJCUkgyVStObEZpSWVjM3NueFlGOWJpUFBwNy8xR1gKUDl1RFU5cXdDOVNxem5HNGdXbk9pa2cydUp1djIxdEo3TmRzZi91Q1huOFpTdmtldlJFMWtNYW9RbzFmOXBtTgozWjJBTHNybXoyWWxvMG5TUUFWYlpNbzZGZHFxQjgwYUNIK0l5OHBXbmFrdVRsMDdYS2t0VFNIamhuVUpBa3lWClo3VUtrU2I1ak91L3grOHByT2dvSDJSNzU4UXQwcng2dkdKT3hxM0o4UWZaaXBPelNENGNldnRuNzY1Y1NVN1IKSVhDYjFWd0FvTmhMaDh6ZVAxdmxibVlxUmo3UUhORGx2VVRheEFJemwrN0xhSzMrSjgweDB1WUEwTkZ1R0Evbwp4Wmx2TEFLd3U2a3ZWL29nMG9teGZITU1xZ0l6QzhHeFRIVU8xSk5QWlp6aUpRSURBUUFCbzBJd1FEQU9CZ05WCkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVYY0ZQS1hVWXMvU0kKMG9xQTMzU2VEM3dTTm53d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKYlBPSzI3azZXbVhDRytTVGFDS21XdQo5Wi9CTXRuVzdxajJ2RXB1bXNQTFQ2YWkrdjV5Tyt1QjRlRzFUNkZzTWM0bWJueXhmSW1NclMxTWNvUnpBM0FuCmExcHZaaXNlejAyQzhrekxaMVFPMC9lT3p1cit3VnZ4UWZNaDNoY29rZmhOREVMTlY4V014YVlvLzRNRjRGNWwKTjZZSDV4Zmp6a0M2YUZEVXhLR2x1TlFDMmQxZGh2MmRKRTdSTEhVdmFLMFlwQVZicTRnb1dkZ1hJR2hsZDE1cQorWUY5K1o3TVo3Vk5nbUtPMVAxM3JFcTE4RElnYWRQaGRUbmJ4Z0NmTWVBLzA1R2p0d0t1dXQ2RHNYenFacE1yCjRjUWxZbENoSnRPUGdta0t4MG80cFpTNVBOTDFKSW1jdTZZQlczb1JXODVCVXl2UUV1UU8yRUJJYTlKRzdrbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  admissionReviewVersions: ["v1"]
  failurePolicy: Ignore
  sideEffects: None
  timeoutSeconds: 5
