apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "host.minikube.internal"
webhooks:
- name: "host.minikube.internal"
  rules:
  - apiGroups:   [""]
    apiVersions: ["*"]
    operations:  ["*"]
    resources:   ["*"]
    scope:       "*"
  clientConfig:
    url: "https://host.minikube.internal:8000/validate"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFmTVIwd0d3WURWUVFERXhSelpXeG0KTFhOcFoyNWxaQzFyT0hNdFkyVnlkREFlRncweU1qRXlNVE15TURJd016ZGFGdzB6TWpFeU1UQXlNREl3TXpkYQpNQjh4SFRBYkJnTlZCQU1URkhObGJHWXRjMmxuYm1Wa0xXczRjeTFqWlhKME1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXphOTFwUEZBMTJBTTNTa0V2SlY5ejBQd1lJcGZWZ2lsTnFWNncyR0UKTWhmMTVrZDJzS0RMTkVWVE5nY3R2MzVycmtNRjBqVk5BR1JFNHkvKzROdGthNHNKYmJpNFNkQUlsSEoxWktXTApEb1krZ0JQdzE2bmdmRXZkcUliUCt5c09pVjN1Q0RVNHB5NUplc29aS0VYVkowUGNNaTZwU0lrNS8vRjlzWHNFCjlhZkFqaUNiQU8rbnlVWVNTNXNvaUViTGdCWFdNc0pQOGZkRk1TdmZFTkpWSGUyWXNZWlhJczFmNUlQbnpRWEsKQUhpSjZ6V3B4UW1Wdmt4eU15ZFdTN3RnMTVVUlVFemRGK1oyZVZGSVRpRXpHSThoZjRSMm9NN3NodUlSNVQvSQpxZGhLY0duTkt1L0IzNUlDcUVuejFCTjdObEVyd3J5TE05OURyYXpEMXFZZVFRSURBUUFCbzBJd1FEQU9CZ05WCkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVV1cjViR1F6ZldMV3EKMWNubml6L0tGUTgwcCtVd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJVWhjakt0NVROMjQ0REVJdlNYNmQ5bQp6RXJ2bURpc2kwdE0waE5RL2RxY1BMM1RKemw3K0tPS1N6UXdZRUphVHlxT05QRUNscnQvUWlqbVRGMzNFRXhlCmJjQktKMDRvdlU5eWRWdGtVRjB0T3cwWUl6dFoyT1Z4VWh2SzhPb2ZoR0tCNjA5Z0FDRGNZdVNQRDBscVIyUXcKNk1PZFlCNlUwSXQwTzliZUd3RWxkUUtCNDVVWUsxYXdXQUF5K2R3dUE5MUc2eC9HM3EzV1J0SmFiQTJGZS9rVgpucWdabEJOdmpkUzZiOCthempBN2I4NUR2ZGlubmxOWWFOR0phTERhUm9EZlpLa0REaVB6Rk9OUElJOHd6WWZvCjZDZnQ2VDBvT2d4aW14eDVmZ2JIUzVnenFtZ2VUSklsYmcwZVBmbWxjT3VObEtTdjFJV2RPS01INE15d2FTND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  admissionReviewVersions: ["v1"]
  failurePolicy: Fail
  sideEffects: None
  timeoutSeconds: 5
