apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterpolicies.kube-shield.red-labs.co.uk
spec:
  group: kube-shield.red-labs.co.uk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                defaultBehaviour:
                  type: string
                  pattern: '^(IfMatchDeny|IfMatchAllow)$'
                applyOn:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                    required:
                    - apiVersion
                    - kind
                policies:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
                      rules:
                        type: array
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            operator:
                              type: string
                              pattern: '^(GreaterThan|LowerThan|Equal|NotEqual|Regex)$'
                            value:
                              type: string
                    required:
                    - rules
                    - name
              required:
              - defaultBehaviour
              - applyOn
              - policies
  scope: Cluster
  names:
    plural: clusterpolicies
    singular: clusterpolicy
    kind: ClusterPolicy
    shortNames: []